/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerEstoque;
import controller.ControllerFilial;
import controller.ControllerFormaPagamento;
import controller.ControllerItemPedido;
import controller.ControllerProduto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelEstoque;
import model.ModelFormaPagamento;
import model.ModelItemPedido;
import model.ModelProduto;

/**
 *
 * @author bruno
 */
public class ViewItemPedido extends javax.swing.JFrame {

    ModelProduto modelProduto = new ModelProduto();
    ModelItemPedido modelItemPedido = new ModelItemPedido();
    ModelEstoque modelEstoque = new ModelEstoque();

    ControllerEstoque controllerEstoque = new ControllerEstoque();
    ControllerFilial controllerFilial = new ControllerFilial();
    ControllerItemPedido controllerItemPedido = new ControllerItemPedido();
    ControllerProduto controllerProduto = new ControllerProduto();
    ControllerFormaPagamento controllerFormaPagamento = new ControllerFormaPagamento();

    ArrayList<ModelItemPedido> listaModelItemPedido = new ArrayList<>();
    ArrayList<ModelProduto> listaModelProduto = new ArrayList<>();
    ArrayList<ModelEstoque> listaModelEstoque = new ArrayList<>();
    ArrayList<ModelFormaPagamento> listaModelFormaPagamento = new ArrayList<>();

    /**
     * Creates new form ViewItemPedido
     */
    public ViewItemPedido() {
        initComponents();
        setLocationRelativeTo(null);
        preencheTabelaProdutos();
        preencherComboBoxFormaPagamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfCodProduto = new javax.swing.JTextField();
        jbBuscaPorId = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfCodBarrasProd = new javax.swing.JTextField();
        jbBuscaPorCodBarra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        jbBuscaPorDescricao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaProduto = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TabelaItemPedido = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JTextField();
        jbRemover = new javax.swing.JButton();
        jbFinalizarVenda = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbAdicionar = new javax.swing.JButton();
        cbFormaPagamento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Id:");

        jbBuscaPorId.setText("jButton1");
        jbBuscaPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaPorIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Código de barras:");

        jbBuscaPorCodBarra.setText("jButton2");
        jbBuscaPorCodBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaPorCodBarraActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição:");

        jbBuscaPorDescricao.setText("jButton3");
        jbBuscaPorDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaPorDescricaoActionPerformed(evt);
            }
        });

        TabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cod Barras", "Descrição", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaProduto);

        TabelaItemPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Status", "Qtd", "Valor unitário", "Valor total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TabelaItemPedido);

        jLabel4.setText("Qtd:");

        jbRemover.setText("Remover");
        jbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverActionPerformed(evt);
            }
        });

        jbFinalizarVenda.setText("Finalizar venda");
        jbFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizarVendaActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbAdicionar.setText("Adicionar");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });

        cbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Forma de pagamento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfDescricao)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbBuscaPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfCodBarrasProd, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbBuscaPorDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jbBuscaPorCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jbRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbFinalizarVenda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAdicionar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscaPorId)
                            .addComponent(tfCodBarrasProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscaPorCodBarra))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscaPorDescricao))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jbAdicionar)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRemover)
                    .addComponent(jbCancelar)
                    .addComponent(jbFinalizarVenda))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscaPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaPorIdActionPerformed
        // TODO add your handling code here:
        // Busca um produto no banco
        DefaultTableModel modelo = (DefaultTableModel) this.TabelaProduto.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.TabelaProduto.setRowSorter(classificador);

        //String txtId = tfId.getText();
        //String txtCodBarras = tfCodBarras.getText();
        String txt = tfCodProduto.getText();

        classificador.setRowFilter(RowFilter.regexFilter(txt, 0));
    }//GEN-LAST:event_jbBuscaPorIdActionPerformed

    private void jbBuscaPorCodBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaPorCodBarraActionPerformed
        // Busca um produto no banco
        DefaultTableModel modelo = (DefaultTableModel) this.TabelaProduto.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.TabelaProduto.setRowSorter(classificador);

        //String txtId = tfId.getText();
        //String txtCodBarras = tfCodBarras.getText();
        String txt = tfCodBarrasProd.getText();

        classificador.setRowFilter(RowFilter.regexFilter(txt, 1));
    }//GEN-LAST:event_jbBuscaPorCodBarraActionPerformed

    private void jbBuscaPorDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaPorDescricaoActionPerformed
        // Busca um produto no banco
        DefaultTableModel modelo = (DefaultTableModel) this.TabelaProduto.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.TabelaProduto.setRowSorter(classificador);

        //String txtId = tfId.getText();
        //String txtCodBarras = tfCodBarras.getText();
        String txt = tfDescricao.getText();

        classificador.setRowFilter(RowFilter.regexFilter(txt, 2));
    }//GEN-LAST:event_jbBuscaPorDescricaoActionPerformed

    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
        // TODO add your handling code here:
        limparCampos();
        modelItemPedido.setStatus("Cancelado");
    }//GEN-LAST:event_jbRemoverActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        /**
         * Preenche a tabela de itemPedido com os produtos do banco
         */

        int linha = this.TabelaProduto.getSelectedRow();
        int idProdutoaux = 0;
        int idEstoque = 0;
        int quantidade = 0;

        try {
            int idProduto = (int) this.TabelaProduto.getValueAt(linha, 0);
            modelProduto = controllerProduto.retornarProdutoController(idProduto);

            modelItemPedido.setIdProduto(modelProduto.getIdProduto());
            modelItemPedido.setStatus("Ativo");
            modelItemPedido.setQuantidade(Integer.parseInt(this.tfQuantidade.getText()));
            modelItemPedido.setValorUnitario(modelProduto.getValor());
            modelItemPedido.setValorTotal(modelProduto.getValor() * Integer.parseInt(tfQuantidade.getText()));

            preencheTabelaItemProdutos();

            int tamTabela = TabelaItemPedido.getRowCount();

            for (int i = 0; i < tamTabela; i++) {

                idEstoque = controllerEstoque.getEstoquePorProdutoController(idProduto).getIdEstoque();
                modelEstoque.setIdEstoque(idEstoque);
                quantidade = controllerEstoque.getEstoqueController(idEstoque).getQuantidade() - Integer.parseInt(TabelaItemPedido.getValueAt(i, 2).toString());

                if (modelItemPedido.getIdProduto() == idProdutoaux) {
                    limparLinhaTabela(i);
                    JOptionPane.showMessageDialog(this, "Produto já foi adicionado!", "Aviso", JOptionPane.ERROR_MESSAGE);
                }

                idProdutoaux = (int) TabelaItemPedido.getValueAt(i, 0);
            }

            if (quantidade >= 0) {
                modelEstoque.setQuantidade(quantidade);
            } else {
                limparLinhaTabela(0);
                JOptionPane.showMessageDialog(this, "Produtos insuficientes esta quantidade", "Aviso", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.getMessage();
            JOptionPane.showMessageDialog(this, e, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void jbFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizarVendaActionPerformed
        // TODO add your handling code here:
        int idProduto = 0;
        int idEstoque = 0;
        int quantidade = 0;

        listaModelItemPedido = new ArrayList<>();

        int tamTabela = TabelaItemPedido.getRowCount();
        for (int i = 0; i < tamTabela; i++) {

            idProduto = (int) TabelaItemPedido.getValueAt(i, 0);
            modelItemPedido = new ModelItemPedido();
            modelEstoque = new ModelEstoque();
            modelItemPedido.setIdProduto(idProduto);
            modelItemPedido.setStatus("Processado");
            modelItemPedido.setQuantidade((int) TabelaItemPedido.getValueAt(i, 2));
            modelItemPedido.setValorUnitario((double) TabelaItemPedido.getValueAt(i, 3));
            modelItemPedido.setValorTotal((double) TabelaItemPedido.getValueAt(i, 4));
            modelItemPedido.setIdFormaPagamento(controllerFormaPagamento.getFormaPagamentoPorTipoController((cbFormaPagamento.getSelectedItem().toString())).getIdFormaPagamento());

            listaModelItemPedido.add(modelItemPedido);
            listaModelEstoque.add(modelEstoque);
        }

        //Salva os produtos da venda
        if (controllerItemPedido.salvarItemPedidoController(listaModelItemPedido)) {
            controllerEstoque.atualizarDadoEstoqueController(listaModelEstoque);
            JOptionPane.showMessageDialog(this, "Item de pedido adicionado!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao inserir produto ao pedido!", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbFinalizarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewItemPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewItemPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewItemPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewItemPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewItemPedido().setVisible(true);
            }
        });
    }

    /**
     * Preenche a tabela de produtos com os produtos do banco
     */
    private void preencheTabelaProdutos() {
        listaModelProduto = controllerProduto.retornarListaProdutoController();
        DefaultTableModel modelo = (DefaultTableModel) TabelaProduto.getModel();
        modelo.setNumRows(0);

        //inserir produtos na tabela
        int count = listaModelProduto.size();
        for (int i = 0; i < count; i++) {
            modelo.addRow(new Object[]{
                listaModelProduto.get(i).getIdProduto(),
                listaModelProduto.get(i).getCodBarras(),
                listaModelProduto.get(i).getDescricao(),
                listaModelProduto.get(i).getValor()
            });
        }
    }

    private void preencheTabelaItemProdutos() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaItemPedido.getModel();
        int count = 0;
        for (int i = 0; i < count; i++) {
            modelo.setNumRows(0);
        }

        modelo.addRow(new Object[]{
            modelItemPedido.getIdProduto(),
            modelItemPedido.getStatus(),
            modelItemPedido.getQuantidade(),
            modelItemPedido.getValorUnitario(),
            modelItemPedido.getValorTotal()
        });
    }

    private void limparCampos() {
        int linha = this.TabelaItemPedido.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) TabelaItemPedido.getModel();

        modelo.removeRow(linha);

    }

    private void limparLinhaTabela(int linha) {
        //int linha = this.TabelaItemPedido.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) TabelaItemPedido.getModel();

        modelo.removeRow(linha);

    }

    /**
     * Preenche o comboBox com todas os produtos do banco
     */
    private void preencherComboBoxFormaPagamento() {
        listaModelFormaPagamento = controllerFormaPagamento.getListaFormaPagamentoController();
        cbFormaPagamento.removeAllItems();
        for (int i = 0; i < listaModelFormaPagamento.size(); i++) {
            cbFormaPagamento.addItem(listaModelFormaPagamento.get(i).getTipoPagamento());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaItemPedido;
    private javax.swing.JTable TabelaProduto;
    private javax.swing.JComboBox<String> cbFormaPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbBuscaPorCodBarra;
    private javax.swing.JButton jbBuscaPorDescricao;
    private javax.swing.JButton jbBuscaPorId;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbFinalizarVenda;
    private javax.swing.JButton jbRemover;
    private javax.swing.JTextField tfCodBarrasProd;
    private javax.swing.JTextField tfCodProduto;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfQuantidade;
    // End of variables declaration//GEN-END:variables
}
