/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import controller.ControllerFilial;
import controller.ControllerPedidoEstoque;
import controller.ControllerProduto;
import controller.ControllerUsuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.ModelCliente;
import model.ModelFilial;
import model.ModelPedidoEstoque;
import model.ModelProduto;
import model.ModelUsuario;

/**
 *
 * @author bruno
 */
public class ViewPedidoEstoque extends javax.swing.JFrame {

    ControllerPedidoEstoque controllerPedidoEstoque = new ControllerPedidoEstoque();
    ArrayList<ModelPedidoEstoque> listaModelPedidoEstoque = new ArrayList<>();
    ModelPedidoEstoque modelPedidoEstoque = new ModelPedidoEstoque();
    
    ArrayList<ModelFilial> listaModelFilial = new ArrayList<>();
    ControllerFilial controllerFilial = new ControllerFilial();
    
    ArrayList<ModelUsuario> listaModelUsuario = new ArrayList<>();
    ControllerUsuario controllerUsuario = new ControllerUsuario();
    
    ArrayList<ModelProduto> listaModelProduto = new ArrayList<>();
    ControllerProduto controllerProduto = new ControllerProduto();
    
    ArrayList<ModelCliente> listaModelCliente = new ArrayList<>();
    ControllerCliente controllerCliente = new ControllerCliente();
    
    ModelFilial modelFilial = new ModelFilial();
    ModelProduto modelProduto = new ModelProduto();
    ModelUsuario modelUsuario = new ModelUsuario();
    ModelCliente modelCliente = new ModelCliente();
    
    /**
     * Creates new form ViewPedidoEstoque
     */
    public ViewPedidoEstoque() {
        initComponents();
        preencherComboBoxFilial();
        preencherComboBoxProduto();
        preencherComboBoxUsuario();
        preencherComboBoxCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbFilial = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbUsuario = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbProduto = new javax.swing.JComboBox<>();
        jbPedidoEntrada = new javax.swing.JButton();
        jbPedidoSaida = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfCodFilial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfCodUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfCodCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfCodProduto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfObservacao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pedido");

        jLabel1.setText("Filial:");

        cbFilial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFilial.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbFilialPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilialActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuario:");

        cbUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbUsuario.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbUsuarioPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel3.setText("Cliente:");

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel4.setText("Produto:");

        cbProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProduto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbProdutoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jbPedidoEntrada.setText("Pedido Entrada");

        jbPedidoSaida.setText("Pedido Saída");
        jbPedidoSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPedidoSaidaActionPerformed(evt);
            }
        });

        jLabel5.setText("Id Filial");

        jLabel6.setText("Id Usuário");

        tfCodUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodUsuarioActionPerformed(evt);
            }
        });

        jLabel7.setText("Id Cliente");

        jLabel8.setText("Id Produto");

        jLabel9.setText("Observação de entrega:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jbPedidoEntrada)
                        .addGap(67, 67, 67)
                        .addComponent(jbPedidoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfCodFilial)
                                    .addComponent(tfCodCliente))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(cbFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCodUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(tfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tfObservacao))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPedidoEntrada)
                    .addComponent(jbPedidoSaida))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFilialActionPerformed

    private void jbPedidoSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPedidoSaidaActionPerformed
        // TODO add your handling code here:
        modelPedidoEstoque.setTipo("SAÍDA");
        modelPedidoEstoque.setIdUsuario(Integer.parseInt(tfCodUsuario.getText()));
        modelPedidoEstoque.setIdCliente(Integer.parseInt(tfCodCliente.getText()));
        modelPedidoEstoque.setIdFilial(Integer.parseInt(tfCodFilial.getText()));
        modelPedidoEstoque.setObservacao(tfObservacao.getText());
        
        if(controllerPedidoEstoque.salvarPedidoEstoqueController(modelPedidoEstoque) > 0){
            
            JOptionPane.showMessageDialog(this, "Pedido saída criado com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            //this.preencherTabelaPedidoEstoque();
            
        }else {
            JOptionPane.showMessageDialog(this, "Erro ao criar pedido sáida!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbPedidoSaidaActionPerformed

    private void cbFilialPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbFilialPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if(cbFilial.isPopupVisible()){
            modelFilial = controllerFilial.getFilialController(cbFilial.getSelectedItem().toString());
            tfCodFilial.setText(String.valueOf(modelFilial.getIdFilial()));
        }
    }//GEN-LAST:event_cbFilialPopupMenuWillBecomeInvisible

    private void tfCodUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodUsuarioActionPerformed

    private void cbUsuarioPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbUsuarioPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if(cbUsuario.isPopupVisible()){
            modelUsuario = controllerUsuario.getUsuarioController(cbUsuario.getSelectedItem().toString());
            tfCodUsuario.setText(String.valueOf(modelUsuario.getIdUsuario()));
        }
    }//GEN-LAST:event_cbUsuarioPopupMenuWillBecomeInvisible

    private void cbClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbClientePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if(cbCliente.isPopupVisible()){
            modelCliente = controllerCliente.retornarClienteController(cbCliente.getSelectedItem().toString());
            tfCodCliente.setText(String.valueOf(modelCliente.getIdCliente()));
        }
    }//GEN-LAST:event_cbClientePopupMenuWillBecomeInvisible

    private void cbProdutoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbProdutoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if(cbProduto.isPopupVisible()){
            modelProduto = controllerProduto.retornarProdutoController(cbProduto.getSelectedItem().toString());
            tfCodProduto.setText(String.valueOf(modelProduto.getIdProduto()));
        }
    }//GEN-LAST:event_cbProdutoPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPedidoEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPedidoEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPedidoEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPedidoEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPedidoEstoque().setVisible(true);
            }
        });
    }
    
     /**
     * Preenche o comboBox com todas as filiais do banco
     */
    private void preencherComboBoxFilial(){
        listaModelFilial = controllerFilial.getListaFilialController();
        cbFilial.removeAllItems();
        for (int i = 0; i < listaModelFilial.size(); i++) {
            cbFilial.addItem(listaModelFilial.get(i).getNome());
        }
    }
    
     /**
     * Preenche o comboBox com todas os produtos do banco
     */
    private void preencherComboBoxProduto(){
        listaModelProduto = controllerProduto.retornarListaProdutoController();
        cbProduto.removeAllItems();
        for (int i = 0; i < listaModelProduto.size(); i++) {
            cbProduto.addItem(listaModelProduto.get(i).getDescricao());
        }
    }
    
     /**
     * Preenche o comboBox com todas os usuários do banco
     */
    private void preencherComboBoxUsuario(){
        listaModelUsuario = controllerUsuario.getListaUsuarioController();
        cbUsuario.removeAllItems();
        for (int i = 0; i < listaModelUsuario.size(); i++) {
            cbUsuario.addItem(listaModelUsuario.get(i).getNome());
        }
    }
    
     /**
     * Preenche o comboBox com todas os usuários do banco
     */
    private void preencherComboBoxCliente(){
        listaModelCliente = controllerCliente.retornarListaClienteController();
        cbCliente.removeAllItems();
        for (int i = 0; i < listaModelCliente.size(); i++) {
            cbCliente.addItem(listaModelCliente.get(i).getNome());
        }
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbFilial;
    private javax.swing.JComboBox<String> cbProduto;
    private javax.swing.JComboBox<String> cbUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbPedidoEntrada;
    private javax.swing.JButton jbPedidoSaida;
    private javax.swing.JTextField tfCodCliente;
    private javax.swing.JTextField tfCodFilial;
    private javax.swing.JTextField tfCodProduto;
    private javax.swing.JTextField tfCodUsuario;
    private javax.swing.JTextField tfObservacao;
    // End of variables declaration//GEN-END:variables
}
