/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerEstoque;
import controller.ControllerEstoqueProduto;
import controller.ControllerFilial;
import controller.ControllerProduto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelEstoque;
import model.ModelEstoqueProduto;
import model.ModelFilial;
import model.ModelProduto;

/**
 *
 * @author bruno
 */
public class ViewEstoque extends javax.swing.JFrame {

    String alterarSalvar;

    ControllerEstoqueProduto controllerEstoqueProduto = new ControllerEstoqueProduto();
    ArrayList<ModelEstoqueProduto> listaModelEstoqueProduto = new ArrayList<>();

    ControllerEstoque controllerEstoque = new ControllerEstoque();
    ModelEstoque modelEstoque = new ModelEstoque();

    ControllerFilial controllerFilial = new ControllerFilial();
    ModelFilial modelFilial = new ModelFilial();
    ArrayList<ModelFilial> listaModelFilial = new ArrayList<>();

    ControllerProduto controllerProduto = new ControllerProduto();
    ModelProduto modelProduto = new ModelProduto();
    ArrayList<ModelProduto> listaModelProduto = new ArrayList<>();

    /**
     * Creates new form ViewEstoque
     */
    public ViewEstoque() {
        initComponents();
        preencherComboBoxFilial();
        preencherComboBoxProduto();
        preencherTabelaEstoque();
        preencherComboBoxProduto();
        setLocationRelativeTo(null);
        habilitaDesabilitaCampos(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfCodFilial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbFilial = new javax.swing.JComboBox<>();
        cbProduto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaEstoque = new javax.swing.JTable();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfCodProduto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código Filial:");

        tfCodFilial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodFilialFocusLost(evt);
            }
        });

        jLabel2.setText("Filial:");

        cbFilial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFilial.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbFilialPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilialActionPerformed(evt);
            }
        });

        cbProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProduto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbProdutoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Produto:");

        jLabel4.setText("Qtd:");

        tfQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeActionPerformed(evt);
            }
        });

        TabelaEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Filial", "Produto", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaEstoque);

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jLabel5.setText("Cod Produto");

        tfCodProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodProdutoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jbExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jbNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(tfCodFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(cbFilial, 0, 345, Short.MAX_VALUE)
                                    .addComponent(cbProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(284, 284, 284)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir)
                    .addComponent(jbNovo)
                    .addComponent(jbCancelar)
                    .addComponent(jbSalvar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeActionPerformed

    private void tfCodProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodProdutoFocusLost
        // TODO add your handling code here:
        modelProduto = controllerProduto.retornarProdutoController(Integer.parseInt(tfCodProduto.getText()));
        cbProduto.setSelectedItem(modelProduto.getDescricao());
    }//GEN-LAST:event_tfCodProdutoFocusLost

    private void cbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProdutoActionPerformed

    private void cbProdutoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbProdutoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cbProduto.isVisible()) {
            modelProduto = controllerProduto.retornarProdutoController(cbProduto.getSelectedItem().toString());
            tfCodProduto.setText(String.valueOf(modelProduto.getIdProduto()));
        }
    }//GEN-LAST:event_cbProdutoPopupMenuWillBecomeInvisible

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // Salva um estoque no banco
        if (checaEstoqueCadastrado()) {
            JOptionPane.showMessageDialog(this, "Estoque já foi cadastrado para esta filial, clique em 'Alterar', para realizar mudanças", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {

            if (alterarSalvar.equals("salvar")) {
                this.salvarEstoque();
            } else if (alterarSalvar.equals("alterar")) {
                this.atualizarEstoque();
            }
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void cbFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFilialActionPerformed

    private void cbFilialPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbFilialPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cbFilial.isPopupVisible()) {
            modelFilial = controllerFilial.getFilialController(cbFilial.getSelectedItem().toString());
            tfCodFilial.setText(String.valueOf(modelFilial.getIdFilial()));
        }
    }//GEN-LAST:event_cbFilialPopupMenuWillBecomeInvisible

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        //habilitaDesabilitaCampos(true);
        limparCampos();
        habilitaDesabilitaCampos(true);
        alterarSalvar = "salvar";
    }//GEN-LAST:event_jbNovoActionPerformed

    private void tfCodFilialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodFilialFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodFilialFocusLost

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // Exclui um estoque do banco
        excluirEstoque();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        alterarSalvar = "alterar";
        habilitaDesabilitaCampos(true);
        int linha = this.TabelaEstoque.getSelectedRow();

        try {
            int idEstoque = (int) this.TabelaEstoque.getValueAt(linha, 0);
            //recupera dados do banco
            modelEstoque = controllerEstoque.getEstoqueController(idEstoque);
            //seta na interface
            this.tfCodProduto.setText(String.valueOf(modelEstoque.getIdProduto()));
            this.tfCodFilial.setText(String.valueOf(modelEstoque.getIdFilial()));
            this.tfQuantidade.setText(String.valueOf(modelEstoque.getQuantidade()));
            // this.cbFilial.getItemAt((this.TabelaEstoque.getValueAt(linha, 2)));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado!", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEstoque().setVisible(true);
            }
        });
    }

    private void salvarEstoque() {
        // Salva um novo estoque no banco
        modelEstoque.setQuantidade(Integer.parseInt(tfQuantidade.getText()));
        modelEstoque.setIdProduto(Integer.parseInt(tfCodProduto.getText()));
        modelEstoque.setIdFilial(Integer.parseInt(tfCodFilial.getText()));

        if (controllerEstoque.salvarEstoqueController(modelEstoque) > 0) {

            JOptionPane.showMessageDialog(this, "Estoque adicionado com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.preencherTabelaEstoque();

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar estoque!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizarEstoque() {
        // Atualiza um produto no banco
        modelEstoque.setQuantidade(Integer.parseInt(this.tfQuantidade.getText()));
        // modelEstoque.setIdProduto(Integer.parseInt(this.tfCodProduto.getText()));
        //modelEstoque.setIdFilial(Integer.parseInt(this.tfCodFilial.getText()));

        if (controllerEstoque.atualizarEstoqueController(modelEstoque)) {

            JOptionPane.showMessageDialog(this, "Estoque atualizado com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.preencherTabelaEstoque();
            limparCampos();
            //habilitaDesabilitaCampos(false);

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar o produto!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void excluirEstoque() {
        int linha = TabelaEstoque.getSelectedRow();
        int codigo = (int) TabelaEstoque.getValueAt(linha, 0);
        if (controllerEstoque.excluirEstoqueController(codigo)) {

            JOptionPane.showMessageDialog(this, "Estoque excluído com sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.preencherTabelaEstoque();
            habilitaDesabilitaCampos(false);

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir estoque", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Preenche o comboBox com todas as filiais do banco
     */
    private void preencherComboBoxFilial() {
        listaModelFilial = controllerFilial.getListaFilialController();
        cbFilial.removeAllItems();
        for (int i = 0; i < listaModelFilial.size(); i++) {
            cbFilial.addItem(listaModelFilial.get(i).getNome());
        }
    }

    /**
     * Preenche o comboBox com todas os produtos do banco
     */
    private void preencherComboBoxProduto() {
        listaModelProduto = controllerProduto.retornarListaProdutoController();
        cbProduto.removeAllItems();
        for (int i = 0; i < listaModelProduto.size(); i++) {
            cbProduto.addItem(listaModelProduto.get(i).getDescricao());
        }
    }

    /**
     * Preenche a tabela com estoques do banco
     */
    private void preencherTabelaEstoque() {

        DefaultTableModel modelo = (DefaultTableModel) TabelaEstoque.getModel();
        listaModelEstoqueProduto = controllerEstoqueProduto.getListaEstoqueProdutoController();
        modelo.setNumRows(0);

        int cont = listaModelEstoqueProduto.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelEstoqueProduto.get(i).getModelEstoque().getIdEstoque(),
                listaModelEstoqueProduto.get(i).getModelEstoque().getIdFilial(),
                listaModelEstoqueProduto.get(i).getModelEstoque().getIdProduto(),
                listaModelEstoqueProduto.get(i).getModelEstoque().getQuantidade()
            });
        }

    }

    private void limparCampos() {
        tfCodFilial.setText("");
        tfCodProduto.setText("");
        tfQuantidade.setText("");
    }

    /**
     * Habilita e desabilita campos do formulário
     *
     * @param condicao
     */
    private void habilitaDesabilitaCampos(boolean condicao) {
        tfCodFilial.setEnabled(condicao);
        tfCodProduto.setEnabled(condicao);
        tfQuantidade.setEnabled(condicao);
        cbFilial.setEnabled(condicao);
        cbProduto.setEnabled(condicao);
    }

    private boolean checaEstoqueCadastrado() {
        if (Integer.parseInt(tfCodFilial.getText()) == controllerEstoque.getEstoquePorFilialProdutoController(Integer.parseInt(tfCodFilial.getText()), Integer.parseInt(tfCodProduto.getText())).getIdFilial()
                && Integer.parseInt(tfCodProduto.getText()) == controllerEstoque.getEstoquePorFilialProdutoController(Integer.parseInt(tfCodFilial.getText()), Integer.parseInt(tfCodProduto.getText())).getIdProduto()) {
            return true;
        }
        return false;
    }

    /**
     * private boolean checaEstoqueProduto(int idProduto){ modelEstoque =
     * controllerEstoque.getEstoquePorProdutoController(idProduto);
     * if(modelEstoque != null){ return true; }else{ return false; } }*
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaEstoque;
    private javax.swing.JComboBox<String> cbFilial;
    private javax.swing.JComboBox<String> cbProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JTextField tfCodFilial;
    private javax.swing.JTextField tfCodProduto;
    private javax.swing.JTextField tfQuantidade;
    // End of variables declaration//GEN-END:variables
}
